type: Epic
name: Melhoria
description: Registrar uma melhoria ou iniciativa.
body:
  - type: textarea
    id: melhoria
    attributes:
      label: Descrição da melhoria
      description: Descreva a melhoria solicitada, o problema atual e o resultado esperado.
      placeholder: Explique de forma clara o que precisa ser melhorado.
    validations:
      required: true
